title: using-thonny
hero_image: images/banner.png
description: using-thonny description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-14"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
